### ISSUE TITLE
Defining features

### ISSUE THREAD

**Issue by sam31987** [eraclitux/machine-learning-netflow#2]
Hi 
 I wanted some information on how these features are defined,
In the link,
https://github.com/eraclitux/machine-learning-netflow/blob/master/machinelearning-netflow.ipynb

there is mention of  features :duration, number of flows, total number of packets. total bytes,packets per second ,bit per second, bit per packet

could you share the mathematical formula that is used to define these features from raw netflow data?

Thanks!

**Comment by eraclitux** [comment]
Hi,
`nfdump` was used to extract features from raw netflow data.
http://nfdump.sourceforge.net/
